# Generated by Django 4.0 on 2021-12-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=200)),
                ('collection_started_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('game_publisher', models.CharField(max_length=200)),
                ('game_bgg_url', models.CharField(max_length=200)),
                ('game_pub_date', models.DateTimeField(verbose_name='date published')),
                ('game_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameCollections.gamecollection')),
            ],
        ),
    ]
