# Generated by Django 4.0 on 2021-12-07 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameCollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='gamecollection',
            name='collection_started_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
