# Generated by Django 4.0 on 2021-12-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameCollections', '0002_game_game_added_date_alter_game_game_pub_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
