# Generated by Django 4.0 on 2021-12-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameCollections', '0003_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('game_publisher', models.CharField(max_length=200)),
                ('game_bgg_url', models.CharField(max_length=200)),
                ('game_pub_date', models.DateTimeField(blank=True, verbose_name='date published')),
                ('game_added_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('game_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameCollections.gamecollection')),
            ],
        ),
    ]
